openapi: 3.0.1
info:
  title: Ecommerce APIs
  description: Open API specifications for Ecommerce Application
  version: 1.0.0

paths:

  /products:
    get:
      operationId: getAllProducts

      responses:
        200:
          description: success, list of all products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productList'
        500:
          description: Internal error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /products/{id}:
    get:
      operationId: getProduct
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: productId

      responses:
        200:
          description: success, product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
        404:
          description: product not found
        500:
          description: Internal error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /products/search:
    get:
      operationId: searchProduct
      parameters:
        - in: query
          name: query
          required: true
          schema:
            type: string
          description: List of products

      responses:
        200:
          description: success, product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productList'
        500:
          description: Internal error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /news:
    get:
      operationId: getAllNews

      responses:
        200:
          description: success, list of all new
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/newsList'
        500:
          description: Internal error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /admin/product/add:
    post:
      operationId: addProduct
      description: addProduct

      parameters:
        - in: header
          name: X-API-KEY
          schema:
            type: string
            format: uuid
          required: true

      requestBody:
        description: The required body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'

      responses:
        200:
          description: OK returned if added
        500:
          description: Internal error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        400:
          description: Bad request

  /admin/product/update:
    post:
      operationId: updateProduct
      description: updateProduct

      parameters:
        - in: header
          name: X-API-KEY
          schema:
            type: string
            format: uuid
          required: true

      requestBody:
        description: The required body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'

      responses:
        200:
          description: OK returned if updated
        500:
          description: Internal error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        400:
          description: Bad request

  /admin/product/delete/{id}:
    delete:
      operationId: deleteProduct
      description: deleteProduct

      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: productId
        - in: header
          name: X-API-KEY
          schema:
            type: string
            format: uuid
          required: true

      responses:
        200:
          description: OK
        404:
          description: product not found
        500:
          description: Something not OK

  /admin/news/add:
    post:
      operationId: addNews
      description: addNews

      parameters:
        - in: header
          name: X-API-KEY
          schema:
            type: string
            format: uuid
          required: true

      requestBody:
        description: The required body of news
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/news'

      responses:
        200:
          description: OK returned if added
        500:
          description: Internal error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        400:
          description: Bad request

  /admin/news/update:
    post:
      operationId: updateNews
      description: updateNews

      parameters:
        - in: header
          name: X-API-KEY
          schema:
            type: string
            format: uuid
          required: true

      requestBody:
        description: The required body of news
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/news'

      responses:
        200:
          description: OK returned
        500:
          description: Internal error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        400:
          description: Bad request

  /admin/news/delete/{id}:
    delete:
      operationId: deleteNews
      description: deleteNews

      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: newsId
        - in: header
          name: X-API-KEY
          schema:
            type: string
            format: uuid
          required: true

      responses:
        200:
          description: OK
        404:
          description: product not found
        500:
          description: Something not OK

  /order/{id}:
    get:
      operationId: getOrder
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: orderId
        - in: header
          name: X-API-KEY
          schema:
            type: string
            format: uuid
          required: true

      responses:
        200:
          description: success, order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
        404:
          description: order not found
        500:
          description: Internal error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /order/addProduct:
    post:
      operationId: postFreshOrder
      parameters:
      - in: query
        name: userId
        required: false
        schema:
          type: integer
      - in: header
        name: X-API-KEY
        schema:
          type: string
          format: uuid
        required: true

      requestBody:
        description: The required body of order
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/order'

      responses:
        200:
          description: success, order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
        500:
          description: Internal error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /order/addProduct/{id}:
    post:
      operationId: addToExistingOrder
      parameters:
        - in: header
          name: X-API-KEY
          schema:
            type: string
            format: uuid
          required: true
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: orderId

      requestBody:
        description: The required body of orderProduct
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/orderProduct'

      responses:
        200:
          description: success, order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
        500:
          description: Internal error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:

    order:
      type: object
      required:
        - id
        - name
        - userId
        - totalPrice
        - orderProducts
      properties:
        id:
          type: integer
        name:
          type: string
        userId:
          type: integer
        totalPrice:
          type: number
        orderProducts:
          $ref: '#/components/schemas/orderProducts'

    orderProducts:
      type: array
      items:
        $ref: '#/components/schemas/orderProduct'

    orderProduct:
      type: object
      required:
        - product
        - quantity
      properties:
        product:
          $ref: '#/components/schemas/product'
        quantity:
          type: integer

    productList:
      type: array
      items:
        $ref: '#/components/schemas/product'

    product:
      type: object
      required:
        - id
        - name
        - description
        - price
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: double

    newsList:
      type: array
      items:
        $ref: '#/components/schemas/news'

    news:
      type: object
      required:
        - id
        - title
        - shortDescription
        - longDescription
        - imageUrl
      properties:
        id:
          type: integer
        title:
          type: string
        shortDescription:
          type: string
        longDescription:
          type: string
        imageUrl:
          type: string

    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
